In [1]:
import pandas as pd
import openpyxl

/tmp/ipykernel_78874/38794811.py:1: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


#### Aula 1: CSV

In [10]:
df = pd.read_csv('./dados/superstore_data.csv')
df.head()

Id  Year_Birth   Education Marital_Status   Income  Kidhome  Teenhome  \
0   1826        1970  Graduation       Divorced  84835.0        0         0   
1      1        1961  Graduation         Single  57091.0        0         0   
2  10476        1958  Graduation        Married  67267.0        0         1   
3   1386        1967  Graduation       Together  32474.0        1         1   
4   5371        1989  Graduation         Single  21474.0        1         0   

  Dt_Customer  Recency  MntWines  ...  MntFishProducts  MntSweetProducts  \
0   6/16/2014        0       189  ...              111               189   
1   6/15/2014        0       464  ...                7                 0   
2   5/13/2014        0       134  ...               15                 2   
3   11/5/2014        0        10  ...                0                 0   
4    8/4/2014        0         6  ...               11                 0   

   MntGoldProds  NumDealsPurchases  NumWebPurchases  NumCatalogPurchases  \
0           218                  1                4                    4   
1            37                  1                7                    3   
2            30                  1                3                    2   
3             0                  1                1                    0   
4            34                  2                3                    1   

   NumStorePurchases  NumWebVisitsMonth  Response  Complain  
0                  6                  1         1         0  
1                  7                  5         1         0  
2                  5                  2         0         0  
3                  2                  7         0         0  
4                  2                  7         1         0  

[5 rows x 22 columns]

In [9]:
dados_sem_virgula = pd.read_csv('./dados/superstore_data_ponto_virgula.csv', sep = ';')
dados_sem_virgula.head()

Id  Year_Birth   Education Marital_Status   Income  Kidhome  Teenhome  \
0   1826        1970  Graduation       Divorced  84835.0        0         0   
1      1        1961  Graduation         Single  57091.0        0         0   
2  10476        1958  Graduation        Married  67267.0        0         1   
3   1386        1967  Graduation       Together  32474.0        1         1   
4   5371        1989  Graduation         Single  21474.0        1         0   

  Dt_Customer  Recency  MntWines  ...  MntFishProducts  MntSweetProducts  \
0   6/16/2014        0       189  ...              111               189   
1   6/15/2014        0       464  ...                7                 0   
2   5/13/2014        0       134  ...               15                 2   
3   11/5/2014        0        10  ...                0                 0   
4    8/4/2014        0         6  ...               11                 0   

   MntGoldProds  NumDealsPurchases  NumWebPurchases  NumCatalogPurchases  \
0           218                  1                4                    4   
1            37                  1                7                    3   
2            30                  1                3                    2   
3             0                  1                1                    0   
4            34                  2                3                    1   

   NumStorePurchases  NumWebVisitsMonth  Response  Complain  
0                  6                  1         1         0  
1                  7                  5         1         0  
2                  5                  2         0         0  
3                  2                  7         0         0  
4                  2                  7         1         0  

[5 rows x 22 columns]

In [13]:
# Selecionando linhas
dados_primeiras_linhas = pd.read_csv('./dados/superstore_data.csv',nrows=5)
dados_primeiras_linhas

Id  Year_Birth   Education Marital_Status  Income  Kidhome  Teenhome  \
0   1826        1970  Graduation       Divorced   84835        0         0   
1      1        1961  Graduation         Single   57091        0         0   
2  10476        1958  Graduation        Married   67267        0         1   
3   1386        1967  Graduation       Together   32474        1         1   
4   5371        1989  Graduation         Single   21474        1         0   

  Dt_Customer  Recency  MntWines  ...  MntFishProducts  MntSweetProducts  \
0   6/16/2014        0       189  ...              111               189   
1   6/15/2014        0       464  ...                7                 0   
2   5/13/2014        0       134  ...               15                 2   
3   11/5/2014        0        10  ...                0                 0   
4    8/4/2014        0         6  ...               11                 0   

   MntGoldProds  NumDealsPurchases  NumWebPurchases  NumCatalogPurchases  \
0           218                  1                4                    4   
1            37                  1                7                    3   
2            30                  1                3                    2   
3             0                  1                1                    0   
4            34                  2                3                    1   

   NumStorePurchases  NumWebVisitsMonth  Response  Complain  
0                  6                  1         1         0  
1                  7                  5         1         0  
2                  5                  2         0         0  
3                  2                  7         0         0  
4                  2                  7         1         0  

[5 rows x 22 columns]

In [18]:
# Selecionando colunas especificas

dados_selecao = pd.read_csv('./dados/superstore_data.csv', usecols=['Id', 'Year_Birth', 'Income'])
dados_selecao.head()

Id  Year_Birth   Income
0   1826        1970  84835.0
1      1        1961  57091.0
2  10476        1958  67267.0
3   1386        1967  32474.0
4   5371        1989  21474.0

In [19]:
dados_selecao = pd.read_csv('./dados/superstore_data.csv', usecols=[0,1,4])
dados_selecao

Id  Year_Birth   Income
0      1826        1970  84835.0
1         1        1961  57091.0
2     10476        1958  67267.0
3      1386        1967  32474.0
4      5371        1989  21474.0
...     ...         ...      ...
2235  10142        1976  66476.0
2236   5263        1977  31056.0
2237     22        1976  46310.0
2238    528        1978  65819.0
2239   4070        1969  94871.0

[2240 rows x 3 columns]

In [22]:
dados_selecao.to_csv('./dados/clientes_mercado.csv', index = False)

#### Aula 2: Exel

In [13]:
df = pd.read_excel('./dados/emissoes_CO2.xlsx')

In [3]:
url = 'https://github.com/alura-cursos/Pandas/blob/main/emissoes_CO2.xlsx?raw=True'

In [5]:
df_co2 = pd.read_excel(url)
df_co2.head()

País ISO 3166-1 alpha-3   Ano  Total  Carvão  Oléo  Gás  Cimento  \
0  Afeganistão                AFG  1750    0.0     NaN   NaN  NaN      NaN   
1  Afeganistão                AFG  1751    0.0     NaN   NaN  NaN      NaN   
2  Afeganistão                AFG  1752    0.0     NaN   NaN  NaN      NaN   
3  Afeganistão                AFG  1753    0.0     NaN   NaN  NaN      NaN   
4  Afeganistão                AFG  1754    0.0     NaN   NaN  NaN      NaN   

   Queima  Outro  Per Capita  
0     NaN    NaN         NaN  
1     NaN    NaN         NaN  
2     NaN    NaN         NaN  
3     NaN    NaN         NaN  
4     NaN    NaN         NaN

In [6]:
pd.ExcelFile(url).sheet_names

['emissoes_C02', 'emissoes_percapita', 'fontes']

In [7]:
percapita = pd.read_excel(url, sheet_name='emissoes_percapita')

In [14]:
percapita.head()

País ISO 3166-1 alpha-3   Ano  Total  Carvão  Óleo  Gás  Cimento  \
0  Afeganistão                AFG  1750    NaN     NaN   NaN  NaN      NaN   
1  Afeganistão                AFG  1751    NaN     NaN   NaN  NaN      NaN   
2  Afeganistão                AFG  1752    NaN     NaN   NaN  NaN      NaN   
3  Afeganistão                AFG  1753    NaN     NaN   NaN  NaN      NaN   
4  Afeganistão                AFG  1754    NaN     NaN   NaN  NaN      NaN   

   Queima  Outro  
0     NaN    NaN  
1     NaN    NaN  
2     NaN    NaN  
3     NaN    NaN  
4     NaN    NaN

In [18]:
fontes = pd.read_excel(url, sheet_name = 'fontes')

In [19]:
fontes1 = pd.read_excel('./dados/emissoes_CO2.xlsx', sheet_name = 'fontes')

In [20]:
fontes1.head()

País ISO 3166-1 alpha-3   Ano   Total  Carvão    Oléo     Gás  \
0  Afeganistão                AFG  1750  [NONE]  [NONE]  [NONE]  [NONE]   
1  Afeganistão                AFG  1751  [NONE]  [NONE]  [NONE]  [NONE]   
2  Afeganistão                AFG  1752  [NONE]  [NONE]  [NONE]  [NONE]   
3  Afeganistão                AFG  1753  [NONE]  [NONE]  [NONE]  [NONE]   
4  Afeganistão                AFG  1754  [NONE]  [NONE]  [NONE]  [NONE]   

  Cimento  Queima   Outro Per Capita  
0  [NONE]  [NONE]  [NONE]     [NONE]  
1  [NONE]  [NONE]  [NONE]     [NONE]  
2  [NONE]  [NONE]  [NONE]     [NONE]  
3  [NONE]  [NONE]  [NONE]     [NONE]  
4  [NONE]  [NONE]  [NONE]     [NONE]

In [24]:
intervalo = pd.read_excel('./dados/emissoes_CO2.xlsx', sheet_name = 'emissoes_C02', usecols = 'A:D')

In [28]:
intervalo

País ISO 3166-1 alpha-3   Ano         Total
0      Afeganistão                AFG  1750  0.000000e+00
1      Afeganistão                AFG  1751  0.000000e+00
2      Afeganistão                AFG  1752  0.000000e+00
3      Afeganistão                AFG  1753  0.000000e+00
4      Afeganistão                AFG  1754  0.000000e+00
...            ...                ...   ...           ...
63099       Global                WLD  2017  3.609674e+10
63100       Global                WLD  2018  3.682651e+10
63101       Global                WLD  2019  3.708256e+10
63102       Global                WLD  2020  3.526409e+10
63103       Global                WLD  2021  3.712385e+10

[63104 rows x 4 columns]

In [27]:
intervalo2 = pd.read_excel('./dados/emissoes_CO2.xlsx', sheet_name = 'emissoes_C02', usecols = 'A:D', nrows = 10)

In [29]:
intervalo2

País ISO 3166-1 alpha-3   Ano  Total
0  Afeganistão                AFG  1750      0
1  Afeganistão                AFG  1751      0
2  Afeganistão                AFG  1752      0
3  Afeganistão                AFG  1753      0
4  Afeganistão                AFG  1754      0
5  Afeganistão                AFG  1755      0
6  Afeganistão                AFG  1756      0
7  Afeganistão                AFG  1757      0
8  Afeganistão                AFG  1758      0
9  Afeganistão                AFG  1759      0

In [30]:
percapita.to_excel('./dados/co2_percapta.xlsx', index = False)

In [31]:
pd.read_excel('./dados/co2_percapta.xlsx')

País ISO 3166-1 alpha-3   Ano      Total     Carvão       Óleo  \
0      Afeganistão                AFG  1750        NaN        NaN        NaN   
1      Afeganistão                AFG  1751        NaN        NaN        NaN   
2      Afeganistão                AFG  1752        NaN        NaN        NaN   
3      Afeganistão                AFG  1753        NaN        NaN        NaN   
4      Afeganistão                AFG  1754        NaN        NaN        NaN   
...            ...                ...   ...        ...        ...        ...   
63099       Global                WLD  2017  4749682.0  1908857.0  1610910.0   
63100       Global                WLD  2018  4792753.0  1919213.0  1596350.0   
63101       Global                WLD  2019  4775633.0  1896468.0  1589920.0   
63102       Global                WLD  2020  4497423.0  1807760.0  1427353.0   
63103       Global                WLD  2021  4693699.0  1893923.0  1496614.0   

             Gás   Cimento   Queima    Outro  
0            NaN       NaN      NaN      NaN  
1            NaN       NaN      NaN      NaN  
2            NaN       NaN      NaN      NaN  
3            NaN       NaN      NaN      NaN  
4            NaN       NaN      NaN      NaN  
...          ...       ...      ...      ...  
63099   940144.0  198416.0  51579.0  39776.0  
63100   979965.0  204225.0  53634.0  39366.0  
63101   984878.0  208309.0  56569.0  39490.0  
63102   963695.0  208844.0  51981.0  37789.0  
63103  1001585.0  211472.0  52663.0  37443.0  

[63104 rows x 10 columns]

##### Fazendo leitura pelo google planilias

In [ ]:
https://docs.google.com/spreadsheets/d/1lzq0k-41-MbbS63C3Q9i1wPvLkSJt9zhr4Jolt1vEog/edit?usp=sharing

1lzq0k-41-MbbS63C3Q9i1wPvLkSJt9zhr4Jolt1vEog

In [32]:
sheet_id = '1lzq0k-41-MbbS63C3Q9i1wPvLkSJt9zhr4Jolt1vEog'

In [47]:
url = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet'

In [48]:
dados_co2_sheets = pd.read_csv(url)

In [41]:
dados_co2_sheets.head()

País ISO 3166-1 alpha-3   Ano Total Carvão Oléo  Gás Cimento Queima  \
0  Afeganistão                AFG  1750     0    NaN  NaN  NaN     NaN    NaN   
1  Afeganistão                AFG  1751     0    NaN  NaN  NaN     NaN    NaN   
2  Afeganistão                AFG  1752     0    NaN  NaN  NaN     NaN    NaN   
3  Afeganistão                AFG  1753     0    NaN  NaN  NaN     NaN    NaN   
4  Afeganistão                AFG  1754     0    NaN  NaN  NaN     NaN    NaN   

  Outro Per Capita  
0   NaN        NaN  
1   NaN        NaN  
2   NaN        NaN  
3   NaN        NaN  
4   NaN        NaN

In [54]:
# Selecionando emissões percapta
sheet_id = '1lzq0k-41-MbbS63C3Q9i1wPvLkSJt9zhr4Jolt1vEog'
sheet_percapta = 'emissoes_percapta'
url_percapta = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_percapta}'

In [60]:
percapita_sheets = pd.read_csv(url_percapta)
percapita_sheets.head()

País ISO 3166-1 alpha-3   Ano Total Carvão Oléo  Gás Cimento Queima  \
0  Afeganistão                AFG  1750     0    NaN  NaN  NaN     NaN    NaN   
1  Afeganistão                AFG  1751     0    NaN  NaN  NaN     NaN    NaN   
2  Afeganistão                AFG  1752     0    NaN  NaN  NaN     NaN    NaN   
3  Afeganistão                AFG  1753     0    NaN  NaN  NaN     NaN    NaN   
4  Afeganistão                AFG  1754     0    NaN  NaN  NaN     NaN    NaN   

  Outro Per Capita  
0   NaN        NaN  
1   NaN        NaN  
2   NaN        NaN  
3   NaN        NaN  
4   NaN        NaN

In [57]:
# Selecionando fontes de amissão
sheet_id = '1lzq0k-41-MbbS63C3Q9i1wPvLkSJt9zhr4Jolt1vEog'
sheet_fontes = 'fontes'
url_fontes = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_fontes}'

In [59]:
fontes_sheets = pd.read_csv(url_fontes)
fontes_sheets.head()

País ISO 3166-1 alpha-3   Ano   Total  Carvão    Oléo     Gás  \
0  Afeganistão                AFG  1750  [NONE]  [NONE]  [NONE]  [NONE]   
1  Afeganistão                AFG  1751  [NONE]  [NONE]  [NONE]  [NONE]   
2  Afeganistão                AFG  1752  [NONE]  [NONE]  [NONE]  [NONE]   
3  Afeganistão                AFG  1753  [NONE]  [NONE]  [NONE]  [NONE]   
4  Afeganistão                AFG  1754  [NONE]  [NONE]  [NONE]  [NONE]   

  Cimento  Queima   Outro Per Capita  
0  [NONE]  [NONE]  [NONE]     [NONE]  
1  [NONE]  [NONE]  [NONE]     [NONE]  
2  [NONE]  [NONE]  [NONE]     [NONE]  
3  [NONE]  [NONE]  [NONE]     [NONE]  
4  [NONE]  [NONE]  [NONE]     [NONE]

#### Aula 3: Json

In [63]:
df_pacientes = pd.read_json('./dados/pacientes.json')
df_pacientes

ID_paciente Doenca_cardiaca    IMC Fumante Consumo_alcool  AVC  \
0              0             Nao  16.60     Sim            Nao  Nao   
1              1             Nao  20.34     Nao            Nao  Sim   
2              2             Nao  26.58     Sim            Nao  Nao   
3              3             Nao  24.21     Nao            Nao  Nao   
4              4             Nao  23.71     Nao            Nao  Nao   
..           ...             ...    ...     ...            ...  ...   
995          995             Nao  28.29     Sim            Nao  Nao   
996          996             Nao  25.69     Sim            Nao  Nao   
997          997             Sim  26.99     Nao            Nao  Nao   
998          998             Nao  44.29     Nao            Nao  Nao   
999          999             Nao  25.83     Nao            Nao  Nao   

     Saude_fisica  Saude_mental Dificuldade_caminhar Sexo_biologico  \
0               3            30                  Nao       Feminino   
1               0             0                  Nao       Feminino   
2              20            30                  Nao      Masculino   
3               0             0                  Nao       Feminino   
4              28             0                  Sim       Feminino   
..            ...           ...                  ...            ...   
995            10            20                  Nao       Feminino   
996             0             0                  Nao       Feminino   
997             1             0                  Nao      Masculino   
998            30             0                  Sim       Feminino   
999             0             0                  Nao      Masculino   

    Faixa_etaria    Raca Diabetes Atividade_fisica Saude_geral  Horas_sono  \
0          55-59  Branca      Sim              Sim   Muito boa           5   
1        80 ou +  Branca      Nao              Sim   Muito boa           7   
2          65-69  Branca      Sim              Sim    Razoavel           8   
3          75-79  Branca      Nao               No         Boa           6   
4          40-44  Branca      Nao              Sim   Muito boa           8   
..           ...     ...      ...              ...         ...         ...   
995        65-69   Preta      Sim              Sim    Razoavel           8   
996        75-79  Branca      Nao              Sim   Excelente           8   
997        70-74  Branca      Nao              Sim   Muito boa           8   
998        70-74  Branca      Sim               No         Boa           6   
999        70-74   Preta      Sim               No   Excelente           7   

    Asma Doenca_renal Cancer_pele  
0    Sim          Nao         Sim  
1    Nao          Nao         Nao  
2    Sim          Nao         Nao  
3    Nao          Nao         Sim  
4    Nao          Nao         Nao  
..   ...          ...         ...  
995  Nao          Nao         Nao  
996  Nao          Nao         Nao  
997  Nao          Nao         Nao  
998  Sim          Nao         Nao  
999  Nao          Nao         Nao  

[1000 rows x 19 columns]

In [66]:
# Nem todos oa .json são normais, ou seja, a informação é alinhada
df_pacientes_2 = pd.read_json('./dados/pacientes_2.json')
df_pacientes_2

Pesquisa   Ano  \
0  Principais Indicadores de Doenca Cardiaca  2020   
1  Principais Indicadores de Doenca Cardiaca  2020   
2  Principais Indicadores de Doenca Cardiaca  2020   

                                           Pacientes  
0  {'ID': '01', 'Faixa_etaria': '55-59', 'Sexo_bi...  
1  {'ID': '02', 'Faixa_etaria': '80 ou +', 'Sexo_...  
2  {'ID': '03', 'Faixa_etaria': '65-69', 'Sexo_bi...

In [69]:
# Normalizando o arquivo .json
df_normalizado = pd.json_normalize(df_pacientes_2['Pacientes'])
df_normalizado

ID Faixa_etaria Sexo_biologico    Raça    IMC Fumante Consumo_alcool  \
0  01        55-59       Feminino  Branca  16.60     Sim            Nao   
1  02      80 ou +       Feminino  Branca  20.34     Nao            Nao   
2  03        65-69      Masculino  Branca  26.58     Sim            Nao   

   Saude_fisica  Saude_mental Dificuldade_caminhar Atividade_fisica  \
0             3            30                  Nao              Sim   
1             0             0                  Nao              Sim   
2            20            30                  Nao              Sim   

  Saude_geral  Horas_sono                Problemas_saude  
0   Muito boa           5  [Diabetes, Asma, Cancer_pele]  
1   Muito boa           7                          [AVC]  
2   Muito boa           8               [diabetes, Asma]

In [70]:
# Salvando em Json
df_normalizado.to_json('./dados/pacientes_normalizado.json')

#### Aula 4: HTML e XML

In [11]:
dados_html = pd.read_html('./dados/filmes_wikipedia.html')
dados_html

[       0                      1
 0   1998             100 Movies
 1   1999              100 Stars
 2   2000             100 Laughs
 3   2001            100 Thrills
 4   2002           100 Passions
 5   2003  100 Heroes & Villains
 6   2004              100 Songs
 7   2005       100 Movie Quotes
 8   2005              25 Scores
 9   2006             100 Cheers
 10  2006            25 Musicals
 11  2007   100 Movies (Updated)
 12  2008        AFI's 10 Top 10
 13   vte                    vte,
                             Film  Release year              Director  \
 0                   Citizen Kane          1941          Orson Welles   
 1                     Casablanca          1942        Michael Curtiz   
 2                  The Godfather          1972  Francis Ford Coppola   
 3             Gone with the Wind          1939        Victor Fleming   
 4             Lawrence of Arabia          1962            David Lean   
 ..                           ...           ...                   

In [13]:
type(dados_html)

3

In [14]:
len(dados_html)

3

In [19]:
# Acessando uma parte especifica da lista/df 
top_filmes = dados_html[1]
top_filmes

Film  Release year              Director  \
0                   Citizen Kane          1941          Orson Welles   
1                     Casablanca          1942        Michael Curtiz   
2                  The Godfather          1972  Francis Ford Coppola   
3             Gone with the Wind          1939        Victor Fleming   
4             Lawrence of Arabia          1962            David Lean   
..                           ...           ...                   ...   
95                 The Searchers          1956             John Ford   
96              Bringing Up Baby          1938          Howard Hawks   
97                    Unforgiven          1992        Clint Eastwood   
98  Guess Who's Coming to Dinner          1967        Stanley Kramer   
99           Yankee Doodle Dandy          1942        Michael Curtiz   

                      Production companies  Rank  
0                       RKO Radio Pictures     1  
1                    Warner Bros. Pictures     2  
2   Paramount Pictures, Alfran Productions     3  
3          Selznick International Pictures     4  
4                         Horizon Pictures     5  
..                                     ...   ...  
95                  C. V. Whitney Pictures    96  
96                      RKO Radio Pictures    97  
97                     The Malpaso Company    98  
98                       Columbia Pictures    99  
99                   Warner Bros. Pictures   100  

[100 rows x 5 columns]

In [20]:
# Transformando em um arquivo html
top_filmes.to_html('./dados/top_filmes.html')

In [21]:
# Transformando em um arquivo csv
top_filmes.to_csv('./dados/top_filmes.csv', index = False)

In [28]:
# Usando formato XML
dados_imdb = pd.read_xml('./dados/imdb_top_1000.xml')
dados_imdb.head(3)

index                                        Poster_Link  \
0      0  https://m.media-amazon.com/images/M/MV5BMDFkYT...   
1      1  https://m.media-amazon.com/images/M/MV5BM2MyNj...   
2      2  https://m.media-amazon.com/images/M/MV5BMTMxNT...   

               Series_Title Released_Year Certificate  Runtime  \
0  The Shawshank Redemption          1994           A  142 min   
1             The Godfather          1972           A  175 min   
2           The Dark Knight          2008          UA  152 min   

                  Genre  IMDB_Rating  \
0                 Drama          9.3   
1          Crime, Drama          9.2   
2  Action, Crime, Drama          9.0   

                                            Overview  Meta_score  \
0  Two imprisoned men bond over a number of years...        80.0   
1  An organized crime dynasty's aging patriarch t...       100.0   
2  When the menace known as the Joker wreaks havo...        84.0   

               Director           Star1           Star2          Star3  \
0        Frank Darabont     Tim Robbins  Morgan Freeman     Bob Gunton   
1  Francis Ford Coppola   Marlon Brando       Al Pacino     James Caan   
2     Christopher Nolan  Christian Bale    Heath Ledger  Aaron Eckhart   

            Star4  No_of_Votes        Gross  
0  William Sadler      2343110   28,341,469  
1    Diane Keaton      1620367  134,966,411  
2   Michael Caine      2303232  534,858,444

In [30]:
dados_imdb.to_xml('./dados/filmes_imdb.xml')

#### Aula 5: Trabahando com Banco de Dados

##### Criando Banco de dados local

In [1]:
import pandas as pd
import sqlalchemy
from sqlalchemy import create_engine, MetaData, Table, inspect, text

/tmp/ipykernel_123598/2742247562.py:1: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [2]:
import pandas as pd
import sqlalchemy
from sqlalchemy import create_engine, MetaData, Table, inspect, text
engine = create_engine('sqlite:///:memory:')

##### Escrevendo no banco de dados

In [3]:
df_banco = pd.read_csv('./dados/clientes_banco.csv')
df_banco.head()

ID_Cliente  Idade Grau_escolaridade   Estado_civil  Tamanho_familia  \
0     5008804     32   Ensino superior  União-estável                2   
1     5008805     32   Ensino superior  União-estável                2   
2     5008806     58      Ensino médio         Casado                2   
3     5008808     52      Ensino médio       Solteiro                1   
4     5008809     52      Ensino médio       Solteiro                1   

    Categoria_de_renda   Ocupacao  Anos_empregado  Rendimento_anual  \
0            Empregado      Outro              12          427500.0   
1            Empregado      Outro              12          427500.0   
2            Empregado  Segurança               3          112500.0   
3  Associado comercial     Vendas               8          270000.0   
4  Associado comercial     Vendas               8          270000.0   

   Tem_carro                   Moradia  
0          1       Apartamento alugado  
1          1       Apartamento alugado  
2          1  Casa/apartamento próprio  
3          0  Casa/apartamento próprio  
4          0  Casa/apartamento próprio

In [4]:
df_banco.to_sql('clientes', engine, index=False)

438463

In [5]:
inspector = inspect(engine)

In [6]:
print(inspector.get_table_names())

['clientes']


In [7]:
query = 'SELECT * FROM clientes WHERE Categoria_de_renda = "Empregado"'

In [8]:
empregados = pd.read_sql(query, engine)

In [9]:
empregados

ID_Cliente  Idade Grau_escolaridade   Estado_civil  Tamanho_familia  \
0          5008804     32   Ensino superior  União-estável                2   
1          5008805     32   Ensino superior  União-estável                2   
2          5008806     58      Ensino médio         Casado                2   
3          5008815     46   Ensino superior         Casado                2   
4          5112956     46   Ensino superior         Casado                2   
...            ...    ...               ...            ...              ...   
226054     6837905     43      Ensino médio         Casado                3   
226055     6837906     43      Ensino médio         Casado                3   
226056     6839936     34      Ensino médio         Casado                3   
226057     6840222     43      Ensino médio       Solteiro                1   
226058     6842885     51      Ensino médio         Casado                2   

       Categoria_de_renda          Ocupacao  Anos_empregado  Rendimento_anual  \
0               Empregado             Outro              12          427500.0   
1               Empregado             Outro              12          427500.0   
2               Empregado         Segurança               3          112500.0   
3               Empregado     Contabilidade               2          270000.0   
4               Empregado     Contabilidade               2          270000.0   
...                   ...               ...             ...               ...   
226054          Empregado             Outro               7          355050.0   
226055          Empregado             Outro               7          355050.0   
226056          Empregado  Construção Civil               5          135000.0   
226057          Empregado  Construção Civil               8          103500.0   
226058          Empregado            Vendas               3          121500.0   

        Tem_carro                   Moradia  
0               1       Apartamento alugado  
1               1       Apartamento alugado  
2               1  Casa/apartamento próprio  
3               1  Casa/apartamento próprio  
4               1  Casa/apartamento próprio  
...           ...                       ...  
226054          1  Casa/apartamento próprio  
226055          1  Casa/apartamento próprio  
226056          1  Casa/apartamento próprio  
226057          0  Casa/apartamento próprio  
226058          0  Casa/apartamento próprio  

[226059 rows x 11 columns]

In [10]:
empregados.to_sql('Empregados', con = engine, index = False)

226059

In [11]:
pd.read_sql_table('Empregados', engine)

ID_Cliente  Idade Grau_escolaridade   Estado_civil  Tamanho_familia  \
0          5008804     32   Ensino superior  União-estável                2   
1          5008805     32   Ensino superior  União-estável                2   
2          5008806     58      Ensino médio         Casado                2   
3          5008815     46   Ensino superior         Casado                2   
4          5112956     46   Ensino superior         Casado                2   
...            ...    ...               ...            ...              ...   
226054     6837905     43      Ensino médio         Casado                3   
226055     6837906     43      Ensino médio         Casado                3   
226056     6839936     34      Ensino médio         Casado                3   
226057     6840222     43      Ensino médio       Solteiro                1   
226058     6842885     51      Ensino médio         Casado                2   

       Categoria_de_renda          Ocupacao  Anos_empregado  Rendimento_anual  \
0               Empregado             Outro              12          427500.0   
1               Empregado             Outro              12          427500.0   
2               Empregado         Segurança               3          112500.0   
3               Empregado     Contabilidade               2          270000.0   
4               Empregado     Contabilidade               2          270000.0   
...                   ...               ...             ...               ...   
226054          Empregado             Outro               7          355050.0   
226055          Empregado             Outro               7          355050.0   
226056          Empregado  Construção Civil               5          135000.0   
226057          Empregado  Construção Civil               8          103500.0   
226058          Empregado            Vendas               3          121500.0   

        Tem_carro                   Moradia  
0               1       Apartamento alugado  
1               1       Apartamento alugado  
2               1  Casa/apartamento próprio  
3               1  Casa/apartamento próprio  
4               1  Casa/apartamento próprio  
...           ...                       ...  
226054          1  Casa/apartamento próprio  
226055          1  Casa/apartamento próprio  
226056          1  Casa/apartamento próprio  
226057          0  Casa/apartamento próprio  
226058          0  Casa/apartamento próprio  

[226059 rows x 11 columns]

* ` O read_sql serve pra ler uma consulta `

* ` O read_sql_table é para a tabela inteira`

In [12]:
pd.read_sql_table('Empregados', engine, columns=['ID_Cliente', 'Grau_escolaridade', 'Rendimento_anual'])

ID_Cliente Grau_escolaridade  Rendimento_anual
0          5008804   Ensino superior          427500.0
1          5008805   Ensino superior          427500.0
2          5008806      Ensino médio          112500.0
3          5008815   Ensino superior          270000.0
4          5112956   Ensino superior          270000.0
...            ...               ...               ...
226054     6837905      Ensino médio          355050.0
226055     6837906      Ensino médio          355050.0
226056     6839936      Ensino médio          135000.0
226057     6840222      Ensino médio          103500.0
226058     6842885      Ensino médio          121500.0

[226059 rows x 3 columns]

###### Retirando um cliente/registro do BD

In [13]:
query = 'SELECT * FROM clientes'

In [14]:
pd.read_sql(query, engine) 

ID_Cliente  Idade Grau_escolaridade   Estado_civil  Tamanho_familia  \
0          5008804     32   Ensino superior  União-estável                2   
1          5008805     32   Ensino superior  União-estável                2   
2          5008806     58      Ensino médio         Casado                2   
3          5008808     52      Ensino médio       Solteiro                1   
4          5008809     52      Ensino médio       Solteiro                1   
...            ...    ...               ...            ...              ...   
438458     6840104     62      Ensino médio     Divorciado                1   
438459     6840222     43      Ensino médio       Solteiro                1   
438460     6841878     22   Ensino superior       Solteiro                1   
438461     6842765     59      Ensino médio         Casado                2   
438462     6842885     51      Ensino médio         Casado                2   

         Categoria_de_renda          Ocupacao  Anos_empregado  \
0                 Empregado             Outro              12   
1                 Empregado             Outro              12   
2                 Empregado         Segurança               3   
3       Associado comercial            Vendas               8   
4       Associado comercial            Vendas               8   
...                     ...               ...             ...   
438458          Pensionista             Outro               0   
438459            Empregado  Construção Civil               8   
438460  Associado comercial            Vendas               1   
438461          Pensionista             Outro               0   
438462            Empregado            Vendas               3   

        Rendimento_anual  Tem_carro                   Moradia  
0               427500.0          1       Apartamento alugado  
1               427500.0          1       Apartamento alugado  
2               112500.0          1  Casa/apartamento próprio  
3               270000.0          0  Casa/apartamento próprio  
4               270000.0          0  Casa/apartamento próprio  
...                  ...        ...                       ...  
438458          135000.0          0  Casa/apartamento próprio  
438459          103500.0          0  Casa/apartamento próprio  
438460           54000.0          0          Mora com os pais  
438461           72000.0          0  Casa/apartamento próprio  
438462          121500.0          0  Casa/apartamento próprio  

[438463 rows x 11 columns]

In [15]:
query = text('DELETE FROM clientes WHERE ID_Cliente = 5008804')


In [16]:
query = text('DELETE FROM clientes WHERE ID_Cliente=5008804')
with engine.connect() as conn:
    conn.execute(query)
    conn.commit()

In [17]:
pd.read_sql_table('clientes', engine)

ID_Cliente  Idade Grau_escolaridade   Estado_civil  Tamanho_familia  \
0          5008805     32   Ensino superior  União-estável                2   
1          5008806     58      Ensino médio         Casado                2   
2          5008808     52      Ensino médio       Solteiro                1   
3          5008809     52      Ensino médio       Solteiro                1   
4          5008810     52      Ensino médio       Solteiro                1   
...            ...    ...               ...            ...              ...   
438457     6840104     62      Ensino médio     Divorciado                1   
438458     6840222     43      Ensino médio       Solteiro                1   
438459     6841878     22   Ensino superior       Solteiro                1   
438460     6842765     59      Ensino médio         Casado                2   
438461     6842885     51      Ensino médio         Casado                2   

         Categoria_de_renda          Ocupacao  Anos_empregado  \
0                 Empregado             Outro              12   
1                 Empregado         Segurança               3   
2       Associado comercial            Vendas               8   
3       Associado comercial            Vendas               8   
4       Associado comercial            Vendas               8   
...                     ...               ...             ...   
438457          Pensionista             Outro               0   
438458            Empregado  Construção Civil               8   
438459  Associado comercial            Vendas               1   
438460          Pensionista             Outro               0   
438461            Empregado            Vendas               3   

        Rendimento_anual  Tem_carro                   Moradia  
0               427500.0          1       Apartamento alugado  
1               112500.0          1  Casa/apartamento próprio  
2               270000.0          0  Casa/apartamento próprio  
3               270000.0          0  Casa/apartamento próprio  
4               270000.0          0  Casa/apartamento próprio  
...                  ...        ...                       ...  
438457          135000.0          0  Casa/apartamento próprio  
438458          103500.0          0  Casa/apartamento próprio  
438459           54000.0          0          Mora com os pais  
438460           72000.0          0  Casa/apartamento próprio  
438461          121500.0          0  Casa/apartamento próprio  

[438462 rows x 11 columns]

###### Alterando Cliente/Registro do DB

In [18]:
query = text('UPDATE clientes SET Grau_escolaridade = "Ensino superior" WHERE ID_CLIENTE = 5008808')

In [19]:
with engine.connect() as conn:
    conn.execute(query)
    conn.commit()

In [20]:
pd.read_sql_table('clientes', engine)

ID_Cliente  Idade Grau_escolaridade   Estado_civil  Tamanho_familia  \
0          5008805     32   Ensino superior  União-estável                2   
1          5008806     58      Ensino médio         Casado                2   
2          5008808     52   Ensino superior       Solteiro                1   
3          5008809     52      Ensino médio       Solteiro                1   
4          5008810     52      Ensino médio       Solteiro                1   
...            ...    ...               ...            ...              ...   
438457     6840104     62      Ensino médio     Divorciado                1   
438458     6840222     43      Ensino médio       Solteiro                1   
438459     6841878     22   Ensino superior       Solteiro                1   
438460     6842765     59      Ensino médio         Casado                2   
438461     6842885     51      Ensino médio         Casado                2   

         Categoria_de_renda          Ocupacao  Anos_empregado  \
0                 Empregado             Outro              12   
1                 Empregado         Segurança               3   
2       Associado comercial            Vendas               8   
3       Associado comercial            Vendas               8   
4       Associado comercial            Vendas               8   
...                     ...               ...             ...   
438457          Pensionista             Outro               0   
438458            Empregado  Construção Civil               8   
438459  Associado comercial            Vendas               1   
438460          Pensionista             Outro               0   
438461            Empregado            Vendas               3   

        Rendimento_anual  Tem_carro                   Moradia  
0               427500.0          1       Apartamento alugado  
1               112500.0          1  Casa/apartamento próprio  
2               270000.0          0  Casa/apartamento próprio  
3               270000.0          0  Casa/apartamento próprio  
4               270000.0          0  Casa/apartamento próprio  
...                  ...        ...                       ...  
438457          135000.0          0  Casa/apartamento próprio  
438458          103500.0          0  Casa/apartamento próprio  
438459           54000.0          0          Mora com os pais  
438460           72000.0          0  Casa/apartamento próprio  
438461          121500.0          0  Casa/apartamento próprio  

[438462 rows x 11 columns]

##### Desafio

Realizar três atualizações no banco de dados:

Atualizar o registro do cliente de ID 6840104 que teve o rendimento anual alterado para 300000.

Excluir o registro do cliente de ID 5008809, pois essa pessoa não possui mais conta na instituição financeira.

Criar um novo registro de cliente seguindo as especificações abaixo:

ID_Cliente: 6850985

Idade: 33

Grau_escolaridade: Doutorado

Estado_civil: Solteiro

Tamanho_familia: 1

Categoria_de_renda: Empregado

Ocupacao: TI

Anos_empregado: 2

Rendimento_anual: 290000

Tem_carro: 0

Moradia: Casa/apartamento próprio

In [21]:
query = text('UPDATE clientes SET Rendimento_anual = 300000 WHERE ID_Cliente = 6840104')

In [49]:
query = text('DELETE FROM clientes WHERE ID_Cliente = 5008809')

In [22]:
with engine.connect() as conn:
    conn.execute(query)
    conn.commit()

In [23]:
pd.read_sql_table('clientes', engine)

ID_Cliente  Idade Grau_escolaridade   Estado_civil  Tamanho_familia  \
0          5008805     32   Ensino superior  União-estável                2   
1          5008806     58      Ensino médio         Casado                2   
2          5008808     52   Ensino superior       Solteiro                1   
3          5008809     52      Ensino médio       Solteiro                1   
4          5008810     52      Ensino médio       Solteiro                1   
...            ...    ...               ...            ...              ...   
438457     6840104     62      Ensino médio     Divorciado                1   
438458     6840222     43      Ensino médio       Solteiro                1   
438459     6841878     22   Ensino superior       Solteiro                1   
438460     6842765     59      Ensino médio         Casado                2   
438461     6842885     51      Ensino médio         Casado                2   

         Categoria_de_renda          Ocupacao  Anos_empregado  \
0                 Empregado             Outro              12   
1                 Empregado         Segurança               3   
2       Associado comercial            Vendas               8   
3       Associado comercial            Vendas               8   
4       Associado comercial            Vendas               8   
...                     ...               ...             ...   
438457          Pensionista             Outro               0   
438458            Empregado  Construção Civil               8   
438459  Associado comercial            Vendas               1   
438460          Pensionista             Outro               0   
438461            Empregado            Vendas               3   

        Rendimento_anual  Tem_carro                   Moradia  
0               427500.0          1       Apartamento alugado  
1               112500.0          1  Casa/apartamento próprio  
2               270000.0          0  Casa/apartamento próprio  
3               270000.0          0  Casa/apartamento próprio  
4               270000.0          0  Casa/apartamento próprio  
...                  ...        ...                       ...  
438457          300000.0          0  Casa/apartamento próprio  
438458          103500.0          0  Casa/apartamento próprio  
438459           54000.0          0          Mora com os pais  
438460           72000.0          0  Casa/apartamento próprio  
438461          121500.0          0  Casa/apartamento próprio  

[438462 rows x 11 columns]

In [50]:
with engine.connect() as conn:
    conn.execute(query)
    conn.commit()


In [51]:
pd.read_sql_table('clientes', engine)

ID_Cliente  Idade Grau_escolaridade   Estado_civil  Tamanho_familia  \
0          5008805     32   Ensino superior  União-estável                2   
1          5008806     58      Ensino médio         Casado                2   
2          5008808     52   Ensino superior       Solteiro                1   
3          5008810     52      Ensino médio       Solteiro                1   
4          5008811     52      Ensino médio       Solteiro                1   
...            ...    ...               ...            ...              ...   
438457     6840222     43      Ensino médio       Solteiro                1   
438458     6841878     22   Ensino superior       Solteiro                1   
438459     6842765     59      Ensino médio         Casado                2   
438460     6842885     51      Ensino médio         Casado                2   
438461     6850985     33         Doutorado       Solteiro                1   

         Categoria_de_renda          Ocupacao  Anos_empregado  \
0                 Empregado             Outro              12   
1                 Empregado         Segurança               3   
2       Associado comercial            Vendas               8   
3       Associado comercial            Vendas               8   
4       Associado comercial            Vendas               8   
...                     ...               ...             ...   
438457            Empregado  Construção Civil               8   
438458  Associado comercial            Vendas               1   
438459          Pensionista             Outro               0   
438460            Empregado            Vendas               3   
438461            Empregado                TI               2   

        Rendimento_anual  Tem_carro                   Moradia  
0               427500.0          1       Apartamento alugado  
1               112500.0          1  Casa/apartamento próprio  
2               270000.0          0  Casa/apartamento próprio  
3               270000.0          0  Casa/apartamento próprio  
4               270000.0          0  Casa/apartamento próprio  
...                  ...        ...                       ...  
438457          103500.0          0  Casa/apartamento próprio  
438458           54000.0          0          Mora com os pais  
438459           72000.0          0  Casa/apartamento próprio  
438460          121500.0          0  Casa/apartamento próprio  
438461          290000.0          0  Casa/apartamento próprio  

[438462 rows x 11 columns]

In [30]:
query = text('INSERT INTO clientes (ID_Cliente,Idade,Grau_escolaridade,Estado_civilTamanho_familia,Categoria_de_renda,Ocupação,Anos_empregado,Rendimento_anualTem_carro,Moradia)VALUE (6850985,33, "Doutorado", "Solteiro", 1, "Empregado""TI", 290000, 0 , "Casa/apartamento próprio"')

In [32]:
query = text('INSERT INTO clientes (ID_Cliente, Idade, Grau_escolaridade, Estado_civil, ' \
        'Tamanho_familia, Categoria_de_renda, Ocupacao, Anos_empregado, ' \
        'Rendimento_anual, Tem_carro, Moradia) ' \
        'VALUES (6850985, 33, "Doutorado", "Solteiro", 1, "Empregado", "TI", ' \
        '2, 290000, 0, "Casa/apartamento próprio")')

with engine.connect() as conn:
    conn.execute(query)
    conn.commit()

In [34]:
pd.read_sql_table('clientes', engine)

ID_Cliente  Idade Grau_escolaridade   Estado_civil  Tamanho_familia  \
0          5008805     32   Ensino superior  União-estável                2   
1          5008806     58      Ensino médio         Casado                2   
2          5008808     52   Ensino superior       Solteiro                1   
3          5008809     52      Ensino médio       Solteiro                1   
4          5008810     52      Ensino médio       Solteiro                1   
...            ...    ...               ...            ...              ...   
438458     6840222     43      Ensino médio       Solteiro                1   
438459     6841878     22   Ensino superior       Solteiro                1   
438460     6842765     59      Ensino médio         Casado                2   
438461     6842885     51      Ensino médio         Casado                2   
438462     6850985     33         Doutorado       Solteiro                1   

         Categoria_de_renda          Ocupacao  Anos_empregado  \
0                 Empregado             Outro              12   
1                 Empregado         Segurança               3   
2       Associado comercial            Vendas               8   
3       Associado comercial            Vendas               8   
4       Associado comercial            Vendas               8   
...                     ...               ...             ...   
438458            Empregado  Construção Civil               8   
438459  Associado comercial            Vendas               1   
438460          Pensionista             Outro               0   
438461            Empregado            Vendas               3   
438462            Empregado                TI               2   

        Rendimento_anual  Tem_carro                   Moradia  
0               427500.0          1       Apartamento alugado  
1               112500.0          1  Casa/apartamento próprio  
2               270000.0          0  Casa/apartamento próprio  
3               270000.0          0  Casa/apartamento próprio  
4               270000.0          0  Casa/apartamento próprio  
...                  ...        ...                       ...  
438458          103500.0          0  Casa/apartamento próprio  
438459           54000.0          0          Mora com os pais  
438460           72000.0          0  Casa/apartamento próprio  
438461          121500.0          0  Casa/apartamento próprio  
438462          290000.0          0  Casa/apartamento próprio  

[438463 rows x 11 columns]

In [33]:
with engine.connect() as conn:
    conn.execute(query)
    conn.commit()

In [ ]:
import pandas as pd
df = pd.read_sql()